### ISSUE TITLE
"Error authenticating: agent list id failed" when pulling/fetching

### ISSUE THREAD

**Issue by KirillMetrik** [techwizrd/GitKraken#10]
When I try to pull or fetch repository GitKraken throws the above error. I am able to pull/fetch in other UI clients though.

**Comment by fperniavp** [comment]
I have the same problem. 

![image](https://user-images.githubusercontent.com/19207624/26948898-fe861fac-4c65-11e7-9128-8d7f1901527d.png)

Even though I can pull/push using the git terminal

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
