### ISSUE TITLE
Rename project to disambiguate from Axiosoft's GitKraken

### ISSUE THREAD

**Issue by loklaan** [techwizrd/GitKraken#12]
Hey mate,

A friend linked me here to one of your issues, I think as a humorous comment on the dangers (annoyances?) of product name collisions.

Anyway, it would seem you are randomly receiving support-like issues about their product. Maybe you want to rename this repo to something other than GitKraken? Big ask I know.

Sincerely,
- Concerned Internet Person

**Comment by erm3nda** [comment]
If this project was made before the Axiosoft, there's no real nee to edit it.
The name collision (unnafortunated or not) makes people found this Git GUI :)

**Comment by loklaan** [comment]
Don't want this issue hanging around in my dashboard. Best of luck.
