### ISSUE TITLE
Version 1.7.1. crashing on ubuntu

### ISSUE THREAD

**Issue by malhotrachetan** [techwizrd/GitKraken#13]
version 1.7.1     The git-kraken app crashes If i put a wrong git url for cloning a repository.

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.

**Comment by malhotrachetan** [comment]
Hahaaha! Sorry, My bad! i should have get that from README though! Never Mind.
