### ISSUE TITLE
Can't pull/push with Git Kraken

### ISSUE THREAD

**Issue by Azteker** [techwizrd/GitKraken#14]
When I pull/push, it reports "Remote not found". I have Github authentication and the repo is fine in Github. I have no idea what I missed.

**Comment by fperniavp** [comment]
Same problem here, I got this:

![image](https://user-images.githubusercontent.com/19207624/26948800-a8bbea70-4c65-11e7-93ff-b08bf2c136b3.png)

Even though if I use the git terminal I can pull/push

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
