### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by erm3nda** [techwizrd/GitKraken#16]
This happend on the latests version i've installed 2.4.0. Previous releases didn't have that render issue.

I noticed that is somewhat about the rendering of webpages (Electron), because i noticed some similar behavior on the resizing/rendering at Firefox, so maybe is finally a webkit problem...

Image: http://i.imgur.com/R5MMgI2.png

I can still use it, but only because i already know the buttons, otherwise will not be able to use them, as only few pixels of some buttons are visible, while still reponding OK at the mouse click.

See: http://i.imgur.com/nCuYOev.png

Regards.

**Update**

Playing with the window, especially resizing window has fixed the problem, and even if i can see the problem for a second at load, it expands now to the full width.

Now it displays ok each time.

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
