### ISSUE TITLE
There is no way of see my full path files in small screens

### ISSUE THREAD

**Issue by darkyelox** [techwizrd/GitKraken#2]
I have a 1366x768 screen using Ubuntu Gnome 15.10, my screen is small and when i have changes in my local repositories in an Android app i can't know which is which of my files in the unstage files view because the path is long and there is no horizontal scroll, i also cannot see a tooltip with the path of the file if i step over the files, the horizontal scroll does not work even in the preview of the modified files i can't see the whole lines of the file.
![seleccion_001](https://cloud.githubusercontent.com/assets/8183191/13430656/ee7696a4-df93-11e5-8b0a-6f54c8011a6a.png)
![seleccion_002](https://cloud.githubusercontent.com/assets/8183191/13430678/06db18f0-df94-11e5-9a34-b216b7205af8.png)

**Comment by MarcinWieczorek** [comment]
It's not Axosoft's GitKraken.

**Comment by techwizrd** [comment]
I created this repository years before they published their application. It's an unfortunate name collision.

**Comment by MarcinWieczorek** [comment]
You should make them pay loads of money for the name
