### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by intellitour** [techwizrd/GitKraken#21]
GitKraken (latest version), prompts proxy credentials while showing all my previous details (that, by the way did not change, but that is another issue) in clear plain text (login, password, proxy address).

![Issue Screen Capture](https://cloud.githubusercontent.com/assets/5827270/26010137/2030f3ba-3722-11e7-86ed-3050afa0700b.png)

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
