### ISSUE TITLE
How to specify SSH port other than 22?

### ISSUE THREAD

**Issue by ccll** [techwizrd/GitKraken#22]
My ssh server runs on a port other than 22, normally I'd configure in my local SSH config file, but since GitKraken doesn't respect the SSH config, I could not find a way for GitKraken to work with my repo.

**Comment by teknologist** [comment]
Same here

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
