### ISSUE TITLE
Open a repository : Can't read folders names

### ISSUE THREAD

**Issue by jeblister** [techwizrd/GitKraken#23]
In linux Manjaro distribution i can't read folders names with gitraken :
![](https://cldup.com/6OBkiW4gi8.png)

**Comment by ripf** [comment]
Same here with Antergos distro... Please fix :)
![bildschirmfoto vom 2017-06-26 09-46-24](https://user-images.githubusercontent.com/4438716/27529505-15ac990c-5a55-11e7-96f2-0da78cc06702.png)

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
