### ISSUE TITLE
Update buttons at bottom move out of place in smaller windows

### ISSUE THREAD

**Issue by CameronDiver** [techwizrd/GitKraken#25]
![2017-07-21-112825_326x102_scrot](https://user-images.githubusercontent.com/7694128/28459987-e28f14a2-6e07-11e7-932f-4e644465bf83.png)

Arch linux, i3, gitkraken version 2.6.0

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
