### ISSUE TITLE
Cant find Gnome-Keyring although its installed

### ISSUE THREAD

**Issue by Lite5h4dow** [techwizrd/GitKraken#26]
I'm using KDE-Neon (with plasma on top) and I can't seem to get GitKraken to launch successfully, I keep getting this error,
```
libgnome-keyring.so.0: cannot open shared object file: No such file or directory

Error: libgnome-keyring.so.0: cannot open shared object file: No such file or directory
```
However, I have got 'Gnome-keyring' installed.

**Comment by Lite5h4dow** [comment]
is anyone available?

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
