### ISSUE TITLE
File blame bug

### ISSUE THREAD

**Issue by trszdev** [techwizrd/GitKraken#30]
![screenshot_3](https://user-images.githubusercontent.com/9008471/29238784-36128696-7f55-11e7-8a5d-7c4856e74344.png)
Sometimes in file blame im seeing an Unknown author(which really isn't unknown), and clicking on its commit fucks blame history up (most of commits dissapears out of left panel)

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
