### ISSUE TITLE
Stash prevents branch from getting hidden

### ISSUE THREAD

**Issue by trszdev** [techwizrd/GitKraken#31]
Assume this situation: you have two branches A and B. You finished work on A, stashed some changes and checked out to B. You hided all branches from graph except B, but A is still visible because its stash stays visible. Its inconvinient and the only thing you can do - delete A's stash

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
