### ISSUE TITLE
Doesn't work "Search remotes" on gitlab

### ISSUE THREAD

**Issue by Deyter** [techwizrd/GitKraken#35]
**To reproduce:**
- Connect to gitlab account.
- Create SSH keys. (optional)
- Select Repository management->Clone->Gitlab

**Expected:**
- Visible projects from your account (as on github tab).

**Actual:**
- "No match" text.

**Comment by mts88** [comment]
+1 same problem

**Comment by marceloglacial** [comment]
Same problem

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
