### ISSUE TITLE
can't enter commit message

### ISSUE THREAD

**Issue by plaffitt** [techwizrd/GitKraken#37]
Hello,

I didn't find the origin of the bug, but sometimes, when I start to write my commit message, I can only write one letter, then it doesn't take the next keyboard entries. If I click on another commit then come back to my message commit, I can edit it normally.

Is there a way that I can help you to find how to reproduce this bug ?

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
