### ISSUE TITLE
Im getting this error

### ISSUE THREAD

**Issue by jtrent238** [techwizrd/GitKraken#38]
I'm getting this error

![](https://puu.sh/zuj9S/6603234770.png)

**Comment by ArthurDelamare** [comment]
Same for me. I tried to uninstall and install gitgraken, it hasn't change anything.
Any ideas ?

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.

**Comment by jtrent238** [comment]
Oh! :man_facepalming: 

![img](https://media1.tenor.com/images/1bbbca6149126ae20b3523d50e4cbae1/tenor.gif)
