### ISSUE TITLE
Push & Pull fail using GitKraken 3.6.0

### ISSUE THREAD

**Issue by PIPO89** [techwizrd/GitKraken#40]
I'm having this problems with GitKraken.

The problem also appear when i try to clone a repository.

Any idea what could it be?

![image](https://user-images.githubusercontent.com/28579855/40187326-8368d780-59b4-11e8-98aa-96604531ab09.png)

![image](https://user-images.githubusercontent.com/28579855/40187377-939d60bc-59b4-11e8-8075-7621920fb5ad.png)

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
