### ISSUE TITLE
ssh+git protocol not supported

### ISSUE THREAD

**Issue by stat1x** [techwizrd/GitKraken#5]
Hi there,

My remote uses ssh+git protocol which gives an address like this : ssh+git://162630@git.dc2.gpaas.net/john-doe.com.git

When I try to push or pull on it, GitKraken :heart: gives me the following error message : **Push failed : Malformed URL**

Is it possible to add support for ssh+git protocol?

Thanks in advance,
Jérémie

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
