### ISSUE TITLE
Can't pull/push with Git Kraken

### ISSUE THREAD

**Issue by firestar300** [techwizrd/GitKraken#7]
Hi,

I can't pull or push in my repo with Git Kraken v1.2. It returned this error :

`GitKraken push failed : credentials callback returned an invalid cred type`.

However, I can push with the shell. I'm on OSX El Capitan.

**Comment by danmarcell** [comment]
having the same issue here

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.

**Comment by ttortorici** [comment]
So how do you fix this?

**Comment by techwizrd** [comment]
@etort This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision. I have no control over their software. Perhaps you should tweet them at [@gitkraken](https://www.twitter.com/gitkraken).

**Comment by developeranirudhprabhu** [comment]
I faced this issue while i was using a repo on BitBucket. I simply disconnected and reconnected my BitBucket account and it started working normally. Not sure what was the exact issue or its root cause.

**Comment by castrojr913** [comment]
@developeranirudhprabhu Yes, it was the solution. However, I think that GitKrakren team ought to fix that issue, a minor one.

**Comment by jemshit** [comment]
Still having same problem on macos
