### ISSUE TITLE
Stays on top of other apps 

### ISSUE THREAD

**Issue by jmorales4** [techwizrd/GitKraken#8]
Since I installed the latest version yesterday, have this really wierd behavior: the client portion of the window stays on top of all other apps.  Screenshot attached.

Ubuntu 14.04
![gitkrakenontop](https://cloud.githubusercontent.com/assets/3705673/14893258/df2c3cb0-0d2b-11e6-84da-d017473ba8b2.png)

**Comment by techwizrd** [comment]
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.
