### ISSUE TITLE
[Bug] Add remote: No repos in linked account

### ISSUE THREAD

**Issue by luchillo17** [techwizrd/GitKraken#9]
I've linked my account of Github and when i try to add a remote to a project the select says `No Match`.

![image](https://cloud.githubusercontent.com/assets/9698639/16528192/d5a671d8-3f80-11e6-8dfc-daa023a926eb.png)

Here's the related config to my account, i have set it up with an ssh key so it should show all my projects.

![image](https://cloud.githubusercontent.com/assets/9698639/16528219/0e11b5fa-3f81-11e6-9962-9ee274f9ba67.png)

**Comment by luchillo17** [comment]
The same happens with my Bitbucket account, i have that one set also with a different account and ssh-key, but also shows `No Match`.

**Comment by scargill** [comment]
Same here - don't use keys... sourcetree works a treat but I cannot for the life of me get GitKraken to see my local repositories on Bitbucket.

**Comment by luchillo17** [comment]
Idk what happened but it suddenly worked, i think after erasing the current ones and trying again it worked.

**Comment by HSkogmo** [comment]
@Luchillo and @scargill This is not the repo for GitKraken by Axosoft. This repo was created way before Axosoft released their GitKraken application, and is an unfortunate name collision. Please report bugs to feedback@gitkraken.com.

**Comment by luchillo17** [comment]
Say whaaat? now that's a casualty, such a name collision is incredible.

**Comment by dunderjeep** [comment]
Had the same problem - workaround was adding the repo by the url from github repo.
![add remote url](https://cloud.githubusercontent.com/assets/1503826/24862963/f0d9493c-1dcc-11e7-9de5-027ee85fdd04.png)

**Comment by luchillo17** [comment]
@dunderjeep Did you read the previous comment? this seems to be a repo that collides in name with GitKraken source control program made by AxoSoft.

You should ask for support in feedback@gitkraken.com.

**Comment by techwizrd** [comment]
@dunderjeep This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.

**Comment by grantrostig** [comment]
Doesn't work here either.  Simply a bug.  I looks like it don't look at bitbucket to give a list.  Poor documentation too, not sure exactly what it is supposed to do. @dunderjeep 's workaround worked for me. Why is this not fixed?

**Comment by luchillo17** [comment]
@grantrostig Dude look at the comments, this is not the AxoSoft GitKraken repo, just a name collision, you have to reach to the AxoSoft support email.

**Comment by poliquinp** [comment]
I have the same problem. Even if I enter all my details from my BitBucket account and it does not let me save it. If I use the BitBucket, I keep getting No match.

**Comment by techwizrd** [comment]
@poliquinp This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision.

**Comment by LunevNF** [comment]
I can't connect to bitbucket too. And YES - I understand, that this repo is not created by Axosoft. But maybe someone resolves this problem?

**Comment by B4ttleCat** [comment]
This is still an issue for me and I have no idea how to get it to work! So frustrating. (macOS High Sierra and Mojave)

**Comment by LunevNF** [comment]
> 
> 
> This is still an issue for me and I have no idea how to get it to work! So frustrating. (macOS High Sierra and Mojave)

Hi. I was buy "PRO"-version and all works fine now. :)

**Comment by B4ttleCat** [comment]
I accidentally just discovered this is a UI bug for me. Here are the steps to get around it:

1. Open Add Remote, confirm "No Match" under BitBucket Repo dropdown
2. Click folder icon (Repo Management) in top left
3. Close that popover
4. Use Add Remote > Bitbucket Repo dropdown again and you should see your list

I hope that works for others.

**Comment by BR1Software** [comment]
@B4ttleCat - you are a star, it worked for me. Thanks.

**Comment by berkon** [comment]
Oh, that's really a bad bug!

**Comment by ghost** [comment]
Good gravy, good find. That totally fixed it. And yes that is STILL a bad bug.

**Comment by Wndrr** [comment]
That thread just shows how many people simply dump an "I have the same problem" without even reading the previous damn answers! 
I still can't add remotes to GitKraken without using the URL technique, but at least I got a good laugh from this ;-)

**Comment by luchillo17** [comment]
@Wndrr I feel you, this thread has at least 2 comments of mine that explains this is not Axosoft GitKraken.

**Comment by Jehoel** [comment]
@B4ttleCat I tried that now in version 6.2.1, however it still didn't populate my Github repo list.

**Comment by techwizrd** [comment]
@Jehoel 
This isn't Axosoft's GitKraken. I created this repository years before they published their application. It's an unfortunate name collision, and this has been mentioned multiple times on the thread above. Please report bugs to feedback@gitkraken.com.

**Comment by calebfaith-old** [comment]
Sadly for @techwizrd this is one of the first to appear in Google search
